version: '3'

services:
  docker-db-mysql:
    env_file: ./.env
    build:
      context: ./docker/dbmysql
    environment:
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./docker/dbmysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/dbmysql/data:/var/lib/mysql

  docker-php-fpm:
    build:
      context: ./docker/php-fpm
    depends_on:
      - docker-db-mysql
    environment:
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=
    volumes:
      - ./app:/var/www

  docker-nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - docker-php-fpm
    ports:
      - "80:80"
      - "81:81"
      - "82:82"
      - "443:443"
  docker-mailhog:
    build:
      context: ./docker/mailhog
    volumes:
      - ./docker/mailhog/home:/home/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"